Forcing pip version because pip 10 was causing errors:
ImportError: cannot import name 'main'

See https://stackoverflow.com/questions/43675074/python3-6-importerror-cannot-import-name-main-linux-rhel6